/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.sbf.dataplatform.beam;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
