[versions]
apache-beam = "2.49.0"
slf4j = "2.0.7"
dataplatform = "0.0.1"

[libraries]
dataplatform-beam = { module = "br.com.sbf.dataplatform.beam:lib", version.ref = "dataplatform"}

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j"}

beam-java = { module = "org.apache.beam:beam-sdks-java-io-kafka", version.ref = "apache-beam"}

[plugins]
google = { id = "com.google.cloud.artifactregistry.gradle-plugin", version = "2.2.1"}
lombok = { id = "io.freefair.lombok", version = "8.1.0"}